version: '3.8'

services:
  db:
    image: postgres:14.11
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "3000:3000"
  server_api:
    build: .
    command: bundle exec rails s
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - bundle_path:/bundle
    links:
      - db
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./web:/nginx/nginx.conf
    depends_on:
      - server_api
    ports:
      - '443:443'
      - '80:80'
    restart: always

volumes:
  bundle_path:
  postgres_data: