version: '3.8'

services:
  db:
    image: postgres:14.11
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "3000:3000"
  server-api:
    build: .
    command: "./bin/rails server"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db

volumes:
  postgres_data: {}
  app-storage: {}